app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

hello:
  path: /api/v1/hello
  methods: POST
  controller: App\Controller\ApiController::hello
